import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "src/app/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const wolverine = localFont({
  src: "./fonts/Wolverine.ttf",
  variable: "--font-wolverine",
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Xavier's School for the Gifted",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${wolverine.variable} antialiased text-white bg-slate-900 bg-[linear-gradient(rgba(15,23,42,0.7),rgba(15,23,42,0.7)),url('/backgroundimage.jpg')] bg-cover bg-center bg-fixed`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
