//src/app/layout.tsx
import { getPrisma } from "@/lib/prisma";
import { cookies } from "next/headers";
import { decrypt } from "@/lib/session";
import { Science_Gothic } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "src/app/components/Navbar";
import CartSidebar from "./components/CartSidebar";

const scienceGothic = Science_Gothic({
  subsets: ["latin"],
  variable: "--font-science-gothic",
});

const wolverine = localFont({
  src: "./fonts/Wolverine.ttf",
  variable: "--font-wolverine",
  weight: "400",
});

export const metadata = {
  title: "Xavier's School for the Gifted",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const sessionCookie = cookieStore.get("session")?.value;
  const session = await decrypt(sessionCookie);

  const prisma = getPrisma();
  let cartItems: any[] = [];

  // Fetch cart items if the logged-in user is a student
  if (session?.userId && session.role === "STUDENT") {
    cartItems = await prisma.enrollment.findMany({
      where: {
        studentId: Number(session.userId),
        status: "IN_CART",
      },
      include: { course: true },
    });
  }

  return (
    <html lang="en">
      <body className="antialiased bg-slate-900 text-white">
        <Navbar />
        {children}
        {/* Only render the sidebar for students */}
        {session?.role === "STUDENT" && <CartSidebar cartItems={cartItems} />}
      </body>
    </html>
  );
}
